@Enablon.CMS.OptimizeIntegration.DataIngestorAPI_HostAddress = http://localhost:5161

GET {{Enablon.CMS.OptimizeIntegration.DataIngestorAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
